title: Haribo Bot
description: 디스코드에서 노래를 재생할 수 있는 봇입니다. (222,000+ 서버/약 400만(+)명이 봇을 이용 중)
url: https://haribosinging.github.io/
keywords: ["Discord", "Music Bot", "Discord bot", "디스코드", "디코 봇", "디코 노래", "노래 봇", "노래하는하리보", "디스코드 봇"]
timezone: Asia/Seoul
permalink: pretty

about: "디스코드에서 노래를 재생할 수 있는 봇입니다.\n한국어를 지원하며, 222,000+ 서버/약 450만(+)명이 봇을 이용 중입니다."

author:
  codepen: 
  disqus: 
  dribbble: 
  email: shlee1503@naver.com
  facebook: 
  flickr: 
  foursquare: 
  github: JellyBrick # required
  google_analytics: UA-58229531-5
  google_plus: 
  instagram: 
  lastfm: 
  linkedin: 
  name: JellyBrick # required
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  telegram:
  tumblr: 
  twitter: 
  weibo: 
  xing: 
  youtube: 

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

kramdown:
  input: GFM

paginate: 5
paginate_path: "/blog/page/:num/"

sass:
  style: compressed
